### ISSUE TITLE
problems when capturing the flag

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/mod-cfbg#54]
You being like Horde and join in the WSG and join the alliance team, when you are going to capture the Flag of the horde, you are unable to capture it.

Anyone else with this problem?

**Comment by FrancescoBorzi** [comment]
I did not hear anything similar

**Comment by WillzDevs** [comment]
> I did not hear anything similar

Good night,
The part of the flag was fixed, however when I enter warsong as an alliance and the CFBG puts me in the horde, my team gets enemy target and I can't cure them.

Follow the screenshot below:
![WoWScrnShot_061421_222059](https://user-images.githubusercontent.com/67213916/121979216-279bab80-cd60-11eb-80a0-db34452f257a.jpg)

**Comment by WillzDevs** [comment]
@Helias can you help me please? I don't know what to do about it

**Comment by Helias** [comment]
Are you using other modules?
What is the version of Azerothcore? Last version?

**Comment by WillzDevs** [comment]
> Você está usando outros módulos?
> Qual é a v


> Are you using other modules?
> What is the version of Azerothcore? Last version?

Thanks for the feedback Helias, I'm using the latest version.
Using the following modules;
Mod-anticheat
Mod-bg-reward
Mod-cfbg
Mod-eluna-lua-engine
Mod-npc-beastmaster
Mod-npc-free-professions
Mod-spellregulator
Mod-transmog 

When in BG when you join as an Alliance and fall on the horde team, the group becomes an enemy, you can't attack, but you can't heal or anything.

I am using these. Thanks for the help!

**Comment by Helias** [comment]
very strange, it happens continously?
on my server we are using the mod-cfbg too but we didn't encounter this so far, may you forgot tore move the config suggested from the README.

```
Make sure your Battleground.InvitationType is set to 0 in worldserver.conf
```
